import { mongoose } from "mongoose";

const orderItemSchema = new mongoose.Schema({
  // product id is generated by mongoDB
  productId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Product",
  },
  quantity: {
    type: Number,
    required: true,
  },
});

const orderSchema = new mongoose.Schema(
  {
    orderPrice: {
      type: Number,
      required: true,
    },
    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    orderItems: {
      // to help with how many of what ordered, we make another schema
      // array of orderItemSchema
      type: [orderItemSchema],
      /*another approach : 
      type: [
        {
            productId...
        }
      ]*/
    },
    address: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      // enum = choices
      enum: ["PENDING", "CANCELLED", "DELIVERED"],
      default: "PENDING",
    },
  },
  {
    timestamps: true,
  }
);

export const Order = mongoose.model("Order", orderSchema);
